### ISSUE TITLE
Open VSX Listing: Signing the Publisher Agreement

### ISSUE THREAD

**Issue by brianking** [weakish/vscode-complete-statement#10]
Thank you for being part of the Open VSX community by adding your extensions to the Open VSX Registry. Please note that the service was recently transferred to the Eclipse Foundation and urgent action on your part is needed so we can continue to list your extensions. To ensure uninterrupted service, please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf) **as soon as possible**. 

Regrettably, if not soon, your extensions will be delisted and will no longer appear on the site nor be available via the API. If you sign at a later date, your extensions will then be re-activated. The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

Please also note that all extensions MUST have a license in order to be listed.

**Claiming ownership of the namespace for your extension(s)**: We also recommend you do this. To find out how to do this, see:
https://github.com/eclipse/openvsx/wiki/Namespace-Access

Useful links:
[Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf)
[Eclipse Foundation Open VSX Registry Frequently Asked Questions (FAQ)](https://www.eclipse.org/legal/open-vsx-registry-faq/) 

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. Thanks for joining us on this journey as we continue to build the Open VSX community. 
We look forward to continued innovation from you in 2021!

**Comment by weakish** [comment]
Thanks for reminding me this, but I disagrees the Eclipse Publisher Agreement.

> Section 8c You agree to defend, indemnify, and hold harmless us, Eclipse members, agents, officers, directors and employees as applicable, from and against any costs, losses, damages, liabilities or expenses and attorneys’ fees arising from any and all third-party claims alleging that your Offering ... or arising from any dispute between you and a licensee or End User of your Offering, relating to your Offering.

I wrote this extension for my personal use, and put the source code in a public repository because I think others may find it helpful. However, I am poor and cannot afford these possible costs, losses, damages, liabilities or expenses and attorneys’ fees of Eclipse foundation, Eclipse members, agents, officers, directors and employees. If some End User of my extension felt upset and decided to sue Eclipse foundation and related entities, I cannot afford the corresponding fees. Eclipse members includes a lot of large companies, I do not think it is fair to require me to defend, indemnify, and hold harmless them all these possible legal costs.

**Comment by tennox** [comment]
Respect to you that you actually read these things :yum: 

But I would try to convince you to agree either way (as I'm using VSCodium & theia and would like to have your extension available easily):

I'd argue this section merely makes sure that - if you violate anyone's rights with your code (e.g. copyright infringement) - You will not blame Eclipse, but agree to take responsibility.

**Visual Studio marketplace has the [same section](https://cdn.vsassets.io/v/M146_20190123.39/_content/Visual-Studio-Marketplace-Publisher-Agreement.pdf):**

> SECTION 4  Licensing of Offerings and Support. 
> (a)  Licensing of Offerings. You are responsible for licensing or otherwise granting rights to your 
> Offerings, including all Offering Contents associated therewith, to Customers. Such licenses and 
> grants will be between you and Customers and will not create any obligations or responsibilities of 
> any kind for Microsoft. [...]
